model:
  base_learning_rate: 1.0e-05
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: "composition"
    cond_stage_key: "image"
    image_size: 64
    channels: 4
    cond_stage_trainable: False   # Note: different from the one we trained before
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False
    u_cond_percent: 0.2
    
    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [ 1000 ]
        cycle_lengths: [ 10000000000000 ] # incredibly large number to prevent corner cases
        f_start: [ 1.e-6 ]
        f_max: [ 1. ]
        f_min: [ 1. ]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32 # unused
        in_channels: 9
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False
        add_conv_in_front_of_unet: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 512
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPImageEmbedder
      params:
        version: openai-clip-vit-large-patch14

data:
  target: ldm.data.datamodule.DataModuleFromConfig
  dataset_dir: &dataset_dir path-to-openimages
  params:
      batch_size: 16
      num_workers: 16
      wrap: False
      train:
          target: ldm.data.open_images.OpenImageDataset
          params:
              split: train
              dataset_dir: *dataset_dir
              image_size: 512
      validation:
          target: ldm.data.open_images.COCOEEDataset
          params:
              split: test
              dataset_dir: path-to-cocoee
              image_size: 512
      test:
          target: ldm.data.open_images.OpenImageDataset
          params:
              split: validation
              dataset_dir: *dataset_dir
              image_size: 512

lightning:
  trainer:
    max_epochs: 40
    accelerator: gpu
    devices: 8
    num_nodes: 1
    val_check_interval: 1.0
